function macros() {
#macro VERSION 29200
#macro GAME_VERSION_STRING "v2.9.2"
#macro GAME_NAME_STRING "Gang Garrison 2"
#macro GAME_URL_STRING "http://www.ganggarrison.com"
#macro PLUGIN_SOURCE "http://www.ganggarrison.com/plugins/"
#macro PLUGIN_SOURCE_NOTICE "While these plugins have been screened by the Gang Garrison 2 community, they cannot guarantee they are safe."
#macro BACKGROUND_SOURCE "http://www.ganggarrison.com/background.png"
#macro DEVMESSAGES_SOURCE "http://www.ganggarrison.com/devmessages.txt"
#macro DEVMESSAGES_SOURCE_BETA "http://www.ganggarrison.com/devmessages_beta.txt"
#macro UPDATE_SOURCE "http://www.ganggarrison.com/gg2update.zip"
#macro UPDATE_SOURCE_BETA "http://www.ganggarrison.com/gg2update_beta.zip"
#macro LOBBY_SERVER_HOST "ganggarrison.com"
#macro LOBBY_SERVER_PORT 29944
#macro AUTH_SERVER_HOST "ganggarrison.com"
#macro AUTH_SERVER_PORT 45022
#macro PROTOCOL_UUID "b31c2209-4256-9a19-d0ef-c71c5373bd75"
#macro GG2_LOBBY_UUID "1ccf16b1-436d-856f-504d-cc1af306aaa7"
#macro HELLO 0
#macro PLAYER_JOIN 1
#macro PLAYER_LEAVE 2
#macro PLAYER_CHANGETEAM 3
#macro PLAYER_CHANGECLASS 4
#macro PLAYER_SPAWN 5
#macro INPUTSTATE 6
#macro CHANGE_MAP 7
#macro FULL_UPDATE 8
#macro QUICK_UPDATE 9
#macro PLAYER_DEATH 10
#macro SERVER_FULL 11
#macro RED_TEAM_CAP 12
#macro BLUE_TEAM_CAP 13
#macro MAP_END 14
#macro CHAT_BUBBLE 15
#macro BUILD_SENTRY 16
#macro DESTROY_SENTRY 17
#macro BALANCE 18
#macro GRAB_INTEL 19
#macro SCORE_INTEL 20
#macro DROP_INTEL 21
#macro UBER_CHARGED 22
#macro UBER 23
#macro OMNOMNOMNOM 24
#macro PASSWORD_REQUEST 25
#macro PASSWORD_WRONG 27
#macro CAPS_UPDATE 28
#macro CP_CAPTURED 30
#macro PLAYER_CHANGENAME 31
#macro GENERATOR_DESTROY 32
#macro ARENA_WAIT_FOR_PLAYERS 33
#macro ARENA_ENDROUND 34
#macro ARENA_RESTART 35
#macro UNLOCKCP 36
#macro SERVER_KICK 37
#macro KICK 38
#macro KICK_NAME 39
#macro ARENA_STARTROUND 40
#macro TOGGLE_ZOOM 41
#macro RETURN_INTEL 42
#macro INCOMPATIBLE_PROTOCOL 43
#macro JOIN_UPDATE 44
#macro DOWNLOAD_MAP 45
#macro SENTRY_POSITION 46
#macro REWARD_UPDATE 47
#macro REWARD_REQUEST 50
#macro REWARD_CHALLENGE_CODE 51
#macro REWARD_CHALLENGE_RESPONSE 52
#macro MESSAGE_STRING 53
#macro WEAPON_FIRE 54
#macro PLUGIN_PACKET 55
#macro KICK_BAD_PLUGIN_PACKET 56
#macro PING 57
#macro CLIENT_SETTINGS 58
#macro KICK_MULTI_CLIENT 59
#macro RESERVE_SLOT 60
#macro TEAM_RED 0
#macro TEAM_BLUE 1
#macro TEAM_SPECTATOR 2
#macro TEAM_ANY 3
#macro CLASS_SCOUT 0
#macro CLASS_SOLDIER 1
#macro CLASS_SNIPER 2
#macro CLASS_DEMOMAN 3
#macro CLASS_MEDIC 4
#macro CLASS_ENGINEER 5
#macro CLASS_HEAVY 6
#macro CLASS_SPY 7
#macro CLASS_PYRO 8
#macro CLASS_QUOTE 9
#macro CHARACTER_ANIMATION_NORMAL 0
#macro CHARACTER_ANIMATION_INTEL 2
#macro CHARACTER_ANIMATION_LEN 4
#macro MAX_PLAYERNAME_LENGTH 20
#macro STATE_UPDATE 8
#macro KILLS 0
#macro DEATHS 1
#macro CAPS 2
#macro ASSISTS 3
#macro DESTRUCTION 4
#macro STABS 5
#macro HEALING 6
#macro DEFENSES 7
#macro INVULNS 8
#macro BONUS 9
#macro DOMINATIONS 10
#macro REVENGE 11
#macro POINTS 12
#macro ASSIST_TIME 120
#macro NOTICE_NUTSNBOLTS 0
#macro NOTICE_TOOCLOSE 1
#macro NOTICE_AUTOGUNSCRAPPED 2
#macro NOTICE_HAVEINTEL 4
#macro NOTICE_SETCHECKPOINT 5
#macro NOTICE_DESTROYCHECKPOINT 6
#macro NOTICE_CUSTOM 9
#macro PARTICLES_NORMAL 0
#macro PARTICLES_OFF 1
#macro PARTICLES_ALTERNATIVE 2
#macro MOUSE_LEFT 9001
#macro MOUSE_RIGHT 9002
#macro HP_PER_POINT 800
#macro INTEL_MAX_TIMER 900
#macro MUSIC_MENU_ONLY 0
#macro MUSIC_BOTH 1
#macro MUSIC_INGAME_ONLY 2
#macro MUSIC_NONE 3
#macro BOOT_BEHAVIOUR 0
#macro BOOT_STANDARD 0
#macro BOOT_DEBUG 1
#macro STRING 0
#macro REAL 1
#macro BOOL 2
#macro HEX 3
#macro GEAR_PARTY_HAT "PartyHat"
#macro GEAR_CROWN "Crown"
#macro GEAR_NAVIGATORHAT "NavigatorHat"
#macro GEAR_RAYBANN_CAPE "RaybannCape"
#macro GEAR_HAXXY_CAPE "HaxxyCape"



}
