function __global_object_depths() {
	// Initialise the global array that allows the lookup of the depth of a given object
	// GM2.0 does not have a depth on objects so on import from 1.x a global array is created
	// NOTE: MacroExpansion is used to insert the array initialisation at import time
	gml_pragma( "global", "__global_object_depths()");

	// insert the generated arrays here
	global.__objectDepths[0] = 0; // GameServer
	global.__objectDepths[1] = 0; // Client
	global.__objectDepths[2] = 0; // RewardAuthChecker
	global.__objectDepths[3] = 0; // Soldier
	global.__objectDepths[4] = 0; // Pyro
	global.__objectDepths[5] = 0; // Scout
	global.__objectDepths[6] = 0; // Quote
	global.__objectDepths[7] = 0; // Sniper
	global.__objectDepths[8] = 0; // Spy
	global.__objectDepths[9] = 0; // Engineer
	global.__objectDepths[10] = 0; // Medic
	global.__objectDepths[11] = 0; // Demoman
	global.__objectDepths[12] = 0; // Heavy
	global.__objectDepths[13] = 0; // SplashController
	global.__objectDepths[14] = 0; // MenuController
	global.__objectDepths[15] = 1; // MainMenuController
	global.__objectDepths[16] = 0; // DevMessageChecker
	global.__objectDepths[17] = 0; // DevMessagePopup
	global.__objectDepths[18] = 0; // BackgroundDownloader
	global.__objectDepths[19] = 0; // CreditsController
	global.__objectDepths[20] = 0; // LobbySideController
	global.__objectDepths[21] = -1; // LobbyNameController
	global.__objectDepths[22] = 0; // LobbyController
	global.__objectDepths[23] = -10; // ScrollUpO
	global.__objectDepths[24] = -10; // ScrollDownO
	global.__objectDepths[25] = 0; // HostOptionsController
	global.__objectDepths[26] = 0; // AdvHostOptionsController
	global.__objectDepths[27] = 0; // HostWarningsController
	global.__objectDepths[28] = 0; // ClasslimitsMenuController
	global.__objectDepths[29] = -140000; // OptionsController
	global.__objectDepths[30] = -140001; // AdvControlsController
	global.__objectDepths[31] = -140001; // ControlsController
	global.__objectDepths[32] = -140000; // HUDOptionsController
	global.__objectDepths[33] = -140000; // EngineOptionsController
	global.__objectDepths[34] = -130000; // InGameMenuController
	global.__objectDepths[35] = -130000; // BuilderMenuController
	global.__objectDepths[36] = 0; // Server
	global.__objectDepths[37] = 0; // Update
	global.__objectDepths[38] = 0; // SSControl
	global.__objectDepths[39] = 0; // AudioControl
	global.__objectDepths[40] = 0; // Gib
	global.__objectDepths[41] = 0; // Feet
	global.__objectDepths[42] = 0; // RedClump
	global.__objectDepths[43] = 0; // BlueClump
	global.__objectDepths[44] = 0; // Hand
	global.__objectDepths[45] = 0; // Accesory
	global.__objectDepths[46] = 0; // Headgib
	global.__objectDepths[47] = 0; // BloodDrop
	global.__objectDepths[48] = 0; // Blood
	global.__objectDepths[49] = 0; // PartyHat
	global.__objectDepths[50] = 0; // CrownGib
	global.__objectDepths[51] = 0; // NavigatorHatGib
	global.__objectDepths[52] = 0; // XmasHat
	global.__objectDepths[53] = -1; // Shell
	global.__objectDepths[54] = 0; // HatGibBase
	global.__objectDepths[55] = 1; // Player
	global.__objectDepths[56] = 1; // SpyGhost
	global.__objectDepths[57] = 0; // Character
	global.__objectDepths[58] = -1; // Weapon
	global.__objectDepths[59] = 0; // PlayerControl
	global.__objectDepths[60] = -2; // SpeechBubbleO
	global.__objectDepths[61] = 0; // SentryGibs
	global.__objectDepths[62] = 0; // Sentry
	global.__objectDepths[63] = 0; // Explosion
	global.__objectDepths[64] = 0; // Impact
	global.__objectDepths[65] = 0; // LooseSheet
	global.__objectDepths[66] = 1; // DeadGuy
	global.__objectDepths[67] = -110001; // NoticeO
	global.__objectDepths[68] = -109999; // Spectator
	global.__objectDepths[69] = 0; // JoiningPlayer
	global.__objectDepths[70] = -110001; // Balancer
	global.__objectDepths[71] = -110001; // Builder
	global.__objectDepths[72] = 0; // GarrisonBuilderCursorController
	global.__objectDepths[73] = -1; // CollisionDummy
	global.__objectDepths[74] = -2; // SpriteObject
	global.__objectDepths[75] = -110000; // ParallaxController
	global.__objectDepths[76] = 0; // IntelligenceBase
	global.__objectDepths[77] = 0; // Intelligence
	global.__objectDepths[78] = 0; // IntelligenceBaseBlue
	global.__objectDepths[79] = 0; // IntelligenceBaseRed
	global.__objectDepths[80] = -2; // IntelligenceRed
	global.__objectDepths[81] = -2; // IntelligenceBlue
	global.__objectDepths[82] = 0; // ArenaControlPoint
	global.__objectDepths[83] = 0; // Generator
	global.__objectDepths[84] = 0; // GeneratorRed
	global.__objectDepths[85] = 0; // GeneratorBlue
	global.__objectDepths[86] = 0; // CaptureZone
	global.__objectDepths[87] = 0; // ControlPoint
	global.__objectDepths[88] = 0; // ControlPoint1
	global.__objectDepths[89] = 0; // ControlPoint2
	global.__objectDepths[90] = 0; // ControlPoint3
	global.__objectDepths[91] = 0; // ControlPoint4
	global.__objectDepths[92] = 0; // ControlPoint5
	global.__objectDepths[93] = 0; // KothControlPoint
	global.__objectDepths[94] = 0; // KothRedControlPoint
	global.__objectDepths[95] = 0; // KothBlueControlPoint
	global.__objectDepths[96] = 0; // Desensitizer
	global.__objectDepths[97] = 0; // On_Map_End_Trigger_Red
	global.__objectDepths[98] = 0; // On_Map_End_Trigger_Red_Back
	global.__objectDepths[99] = 0; // On_Map_End_Trigger_Blu_Back
	global.__objectDepths[100] = 0; // On_Map_End_Trigger_Blu
	global.__objectDepths[101] = 0; // SpawnRoom
	global.__objectDepths[102] = 0; // SpawnPointRed
	global.__objectDepths[103] = 0; // SpawnPointRed1
	global.__objectDepths[104] = 0; // SpawnPointRed2
	global.__objectDepths[105] = 0; // SpawnPointRed3
	global.__objectDepths[106] = 0; // SpawnPointRed4
	global.__objectDepths[107] = 0; // SpawnPointBlue
	global.__objectDepths[108] = 0; // SpawnPointBlue1
	global.__objectDepths[109] = 0; // SpawnPointBlue2
	global.__objectDepths[110] = 0; // SpawnPointBlue3
	global.__objectDepths[111] = 0; // SpawnPointBlue4
	global.__objectDepths[112] = 0; // HealingCabinet
	global.__objectDepths[113] = 0; // MoveBox
	global.__objectDepths[114] = 0; // MoveBoxRight
	global.__objectDepths[115] = 0; // MoveBoxLeft
	global.__objectDepths[116] = 0; // MoveBoxUp
	global.__objectDepths[117] = 0; // MoveBoxDown
	global.__objectDepths[118] = 0; // KillBox
	global.__objectDepths[119] = 0; // PitFall
	global.__objectDepths[120] = 0; // FragBox
	global.__objectDepths[121] = 0; // Obstacle
	global.__objectDepths[122] = 0; // Gate
	global.__objectDepths[123] = 0; // TeamGate
	global.__objectDepths[124] = 0; // IntelGate
	global.__objectDepths[125] = 0; // RedTeamGate
	global.__objectDepths[126] = 0; // RedTeamGate2
	global.__objectDepths[127] = 0; // BlueTeamGate
	global.__objectDepths[128] = 0; // BlueTeamGate2
	global.__objectDepths[129] = 0; // RedIntelGate
	global.__objectDepths[130] = 0; // RedIntelGate2
	global.__objectDepths[131] = 0; // BlueIntelGate
	global.__objectDepths[132] = 0; // BlueIntelGate2
	global.__objectDepths[133] = 0; // IntelGateVertical
	global.__objectDepths[134] = 0; // IntelGateHorizontal
	global.__objectDepths[135] = 0; // PlayerWall
	global.__objectDepths[136] = 0; // PlayerWallHorizontal
	global.__objectDepths[137] = 0; // DropdownPlatform
	global.__objectDepths[138] = 0; // BulletWall
	global.__objectDepths[139] = 0; // BulletWallHorizontal
	global.__objectDepths[140] = 0; // LeftDoor
	global.__objectDepths[141] = 0; // RightDoor
	global.__objectDepths[142] = 0; // ControlPointSetupGate
	global.__objectDepths[143] = 0; // CharacterCollider
	global.__objectDepths[144] = 0; // MovingPlatform
	global.__objectDepths[145] = 0; // NextAreaO
	global.__objectDepths[146] = 0; // PreviousAreaO
	global.__objectDepths[147] = 0; // LevelEntity
	global.__objectDepths[148] = -1; // Medigun
	global.__objectDepths[149] = -1; // Rifle
	global.__objectDepths[150] = -1; // Minegun
	global.__objectDepths[151] = -1; // Minigun
	global.__objectDepths[152] = -1; // Flamethrower
	global.__objectDepths[153] = -1; // Scattergun
	global.__objectDepths[154] = -1; // Shotgun
	global.__objectDepths[155] = -1; // Rocketlauncher
	global.__objectDepths[156] = 1; // Blade
	global.__objectDepths[157] = -1; // Revolver
	global.__objectDepths[158] = 0; // SentryTurret
	global.__objectDepths[159] = 0; // Rocket
	global.__objectDepths[160] = 0; // Shot
	global.__objectDepths[161] = 0; // StabMask
	global.__objectDepths[162] = 0; // StabAnim
	global.__objectDepths[163] = 0; // Bubble
	global.__objectDepths[164] = 0; // Pop
	global.__objectDepths[165] = 0; // BladeB
	global.__objectDepths[166] = 0; // Flame
	global.__objectDepths[167] = 0; // BurningProjectile
	global.__objectDepths[168] = 0; // Flare
	global.__objectDepths[169] = 1; // MineTrail
	global.__objectDepths[170] = 0; // Mine
	global.__objectDepths[171] = 0; // Needle
	global.__objectDepths[172] = 0; // AirBlastO
	global.__objectDepths[173] = -120001; // CharacterPortraitAnimation
	global.__objectDepths[174] = -120001; // ScoutPortraitAnimation
	global.__objectDepths[175] = -120001; // PyroPortraitAnimation
	global.__objectDepths[176] = -120001; // SoldierPortraitAnimation
	global.__objectDepths[177] = -120001; // HeavyPortraitAnimation
	global.__objectDepths[178] = -120001; // DemomanPortraitAnimation
	global.__objectDepths[179] = -120001; // MedicPortraitAnimation
	global.__objectDepths[180] = -120001; // EngineerPortraitAnimation
	global.__objectDepths[181] = -120001; // SpyPortraitAnimation
	global.__objectDepths[182] = -120001; // SniperPortraitAnimation
	global.__objectDepths[183] = -120001; // RandomPortraitAnimation
	global.__objectDepths[184] = -110000; // CTFHUD
	global.__objectDepths[185] = -110000; // InvasionHUD
	global.__objectDepths[186] = -110000; // ControlPointHUD
	global.__objectDepths[187] = -110000; // FauxCPHUD
	global.__objectDepths[188] = -110000; // ArenaHUD
	global.__objectDepths[189] = -110000; // KothHUD
	global.__objectDepths[190] = -110000; // GeneratorHUD
	global.__objectDepths[191] = -110000; // DKothHUD
	global.__objectDepths[192] = -120000; // TeamDeathmatchHUD
	global.__objectDepths[193] = -120000; // TeamSelectController
	global.__objectDepths[194] = -120000; // ClassSelectController
	global.__objectDepths[195] = -110000; // BubbleMenuZ
	global.__objectDepths[196] = -110000; // BubbleMenuX
	global.__objectDepths[197] = -110000; // BubbleMenuC
	global.__objectDepths[198] = -115000; // ScoreTableController
	global.__objectDepths[199] = 0; // HUD
	global.__objectDepths[200] = -110000; // KillLog
	global.__objectDepths[201] = 0; // RespawnTimer
	global.__objectDepths[202] = -110000; // SentryHealthHud
	global.__objectDepths[203] = -110000; // NutsNBoltsHud
	global.__objectDepths[204] = -110000; // SandwichHud
	global.__objectDepths[205] = -110000; // UberHud
	global.__objectDepths[206] = -110000; // StickyCounter
	global.__objectDepths[207] = -110000; // AmmoCounter
	global.__objectDepths[208] = -130000; // DeathCam
	global.__objectDepths[209] = -110000; // HealthHud
	global.__objectDepths[210] = -110000; // MedicRadar
	global.__objectDepths[211] = -120000; // WinBanner
	global.__objectDepths[212] = -110000; // HealedHud
	global.__objectDepths[213] = -110000; // HealingHud
	global.__objectDepths[214] = 0; // CollisionMapO
	global.__objectDepths[215] = 0; // Point
	global.__objectDepths[216] = 0; // CustomMapO
	global.__objectDepths[217] = 0; // PumpkinGib
	global.__objectDepths[218] = 1; // Ghost
	global.__objectDepths[219] = 0; // Money
	global.__objectDepths[220] = 2; // Tombstone
	global.__objectDepths[221] = 0; // RoomChangeObserver
	global.__objectDepths[222] = 0; // Updater
	global.__objectDepths[223] = 0; // RateController
	global.__objectDepths[224] = 0; // PluginEnvironment


	global.__objectNames[0] = "GameServer";
	global.__objectNames[1] = "Client";
	global.__objectNames[2] = "RewardAuthChecker";
	global.__objectNames[3] = "Soldier";
	global.__objectNames[4] = "Pyro";
	global.__objectNames[5] = "Scout";
	global.__objectNames[6] = "Quote";
	global.__objectNames[7] = "Sniper";
	global.__objectNames[8] = "Spy";
	global.__objectNames[9] = "Engineer";
	global.__objectNames[10] = "Medic";
	global.__objectNames[11] = "Demoman";
	global.__objectNames[12] = "Heavy";
	global.__objectNames[13] = "SplashController";
	global.__objectNames[14] = "MenuController";
	global.__objectNames[15] = "MainMenuController";
	global.__objectNames[16] = "DevMessageChecker";
	global.__objectNames[17] = "DevMessagePopup";
	global.__objectNames[18] = "BackgroundDownloader";
	global.__objectNames[19] = "CreditsController";
	global.__objectNames[20] = "LobbySideController";
	global.__objectNames[21] = "LobbyNameController";
	global.__objectNames[22] = "LobbyController";
	global.__objectNames[23] = "ScrollUpO";
	global.__objectNames[24] = "ScrollDownO";
	global.__objectNames[25] = "HostOptionsController";
	global.__objectNames[26] = "AdvHostOptionsController";
	global.__objectNames[27] = "HostWarningsController";
	global.__objectNames[28] = "ClasslimitsMenuController";
	global.__objectNames[29] = "OptionsController";
	global.__objectNames[30] = "AdvControlsController";
	global.__objectNames[31] = "ControlsController";
	global.__objectNames[32] = "HUDOptionsController";
	global.__objectNames[33] = "EngineOptionsController";
	global.__objectNames[34] = "InGameMenuController";
	global.__objectNames[35] = "BuilderMenuController";
	global.__objectNames[36] = "Server";
	global.__objectNames[37] = "Update";
	global.__objectNames[38] = "SSControl";
	global.__objectNames[39] = "AudioControl";
	global.__objectNames[40] = "Gib";
	global.__objectNames[41] = "Feet";
	global.__objectNames[42] = "RedClump";
	global.__objectNames[43] = "BlueClump";
	global.__objectNames[44] = "Hand";
	global.__objectNames[45] = "Accesory";
	global.__objectNames[46] = "Headgib";
	global.__objectNames[47] = "BloodDrop";
	global.__objectNames[48] = "Blood";
	global.__objectNames[49] = "PartyHat";
	global.__objectNames[50] = "CrownGib";
	global.__objectNames[51] = "NavigatorHatGib";
	global.__objectNames[52] = "XmasHat";
	global.__objectNames[53] = "Shell";
	global.__objectNames[54] = "HatGibBase";
	global.__objectNames[55] = "Player";
	global.__objectNames[56] = "SpyGhost";
	global.__objectNames[57] = "Character";
	global.__objectNames[58] = "Weapon";
	global.__objectNames[59] = "PlayerControl";
	global.__objectNames[60] = "SpeechBubbleO";
	global.__objectNames[61] = "SentryGibs";
	global.__objectNames[62] = "Sentry";
	global.__objectNames[63] = "Explosion";
	global.__objectNames[64] = "Impact";
	global.__objectNames[65] = "LooseSheet";
	global.__objectNames[66] = "DeadGuy";
	global.__objectNames[67] = "NoticeO";
	global.__objectNames[68] = "Spectator";
	global.__objectNames[69] = "JoiningPlayer";
	global.__objectNames[70] = "Balancer";
	global.__objectNames[71] = "Builder";
	global.__objectNames[72] = "GarrisonBuilderCursorController";
	global.__objectNames[73] = "CollisionDummy";
	global.__objectNames[74] = "SpriteObject";
	global.__objectNames[75] = "ParallaxController";
	global.__objectNames[76] = "IntelligenceBase";
	global.__objectNames[77] = "Intelligence";
	global.__objectNames[78] = "IntelligenceBaseBlue";
	global.__objectNames[79] = "IntelligenceBaseRed";
	global.__objectNames[80] = "IntelligenceRed";
	global.__objectNames[81] = "IntelligenceBlue";
	global.__objectNames[82] = "ArenaControlPoint";
	global.__objectNames[83] = "Generator";
	global.__objectNames[84] = "GeneratorRed";
	global.__objectNames[85] = "GeneratorBlue";
	global.__objectNames[86] = "CaptureZone";
	global.__objectNames[87] = "ControlPoint";
	global.__objectNames[88] = "ControlPoint1";
	global.__objectNames[89] = "ControlPoint2";
	global.__objectNames[90] = "ControlPoint3";
	global.__objectNames[91] = "ControlPoint4";
	global.__objectNames[92] = "ControlPoint5";
	global.__objectNames[93] = "KothControlPoint";
	global.__objectNames[94] = "KothRedControlPoint";
	global.__objectNames[95] = "KothBlueControlPoint";
	global.__objectNames[96] = "Desensitizer";
	global.__objectNames[97] = "On_Map_End_Trigger_Red";
	global.__objectNames[98] = "On_Map_End_Trigger_Red_Back";
	global.__objectNames[99] = "On_Map_End_Trigger_Blu_Back";
	global.__objectNames[100] = "On_Map_End_Trigger_Blu";
	global.__objectNames[101] = "SpawnRoom";
	global.__objectNames[102] = "SpawnPointRed";
	global.__objectNames[103] = "SpawnPointRed1";
	global.__objectNames[104] = "SpawnPointRed2";
	global.__objectNames[105] = "SpawnPointRed3";
	global.__objectNames[106] = "SpawnPointRed4";
	global.__objectNames[107] = "SpawnPointBlue";
	global.__objectNames[108] = "SpawnPointBlue1";
	global.__objectNames[109] = "SpawnPointBlue2";
	global.__objectNames[110] = "SpawnPointBlue3";
	global.__objectNames[111] = "SpawnPointBlue4";
	global.__objectNames[112] = "HealingCabinet";
	global.__objectNames[113] = "MoveBox";
	global.__objectNames[114] = "MoveBoxRight";
	global.__objectNames[115] = "MoveBoxLeft";
	global.__objectNames[116] = "MoveBoxUp";
	global.__objectNames[117] = "MoveBoxDown";
	global.__objectNames[118] = "KillBox";
	global.__objectNames[119] = "PitFall";
	global.__objectNames[120] = "FragBox";
	global.__objectNames[121] = "Obstacle";
	global.__objectNames[122] = "Gate";
	global.__objectNames[123] = "TeamGate";
	global.__objectNames[124] = "IntelGate";
	global.__objectNames[125] = "RedTeamGate";
	global.__objectNames[126] = "RedTeamGate2";
	global.__objectNames[127] = "BlueTeamGate";
	global.__objectNames[128] = "BlueTeamGate2";
	global.__objectNames[129] = "RedIntelGate";
	global.__objectNames[130] = "RedIntelGate2";
	global.__objectNames[131] = "BlueIntelGate";
	global.__objectNames[132] = "BlueIntelGate2";
	global.__objectNames[133] = "IntelGateVertical";
	global.__objectNames[134] = "IntelGateHorizontal";
	global.__objectNames[135] = "PlayerWall";
	global.__objectNames[136] = "PlayerWallHorizontal";
	global.__objectNames[137] = "DropdownPlatform";
	global.__objectNames[138] = "BulletWall";
	global.__objectNames[139] = "BulletWallHorizontal";
	global.__objectNames[140] = "LeftDoor";
	global.__objectNames[141] = "RightDoor";
	global.__objectNames[142] = "ControlPointSetupGate";
	global.__objectNames[143] = "CharacterCollider";
	global.__objectNames[144] = "MovingPlatform";
	global.__objectNames[145] = "NextAreaO";
	global.__objectNames[146] = "PreviousAreaO";
	global.__objectNames[147] = "LevelEntity";
	global.__objectNames[148] = "Medigun";
	global.__objectNames[149] = "Rifle";
	global.__objectNames[150] = "Minegun";
	global.__objectNames[151] = "Minigun";
	global.__objectNames[152] = "Flamethrower";
	global.__objectNames[153] = "Scattergun";
	global.__objectNames[154] = "Shotgun";
	global.__objectNames[155] = "Rocketlauncher";
	global.__objectNames[156] = "Blade";
	global.__objectNames[157] = "Revolver";
	global.__objectNames[158] = "SentryTurret";
	global.__objectNames[159] = "Rocket";
	global.__objectNames[160] = "Shot";
	global.__objectNames[161] = "StabMask";
	global.__objectNames[162] = "StabAnim";
	global.__objectNames[163] = "Bubble";
	global.__objectNames[164] = "Pop";
	global.__objectNames[165] = "BladeB";
	global.__objectNames[166] = "Flame";
	global.__objectNames[167] = "BurningProjectile";
	global.__objectNames[168] = "Flare";
	global.__objectNames[169] = "MineTrail";
	global.__objectNames[170] = "Mine";
	global.__objectNames[171] = "Needle";
	global.__objectNames[172] = "AirBlastO";
	global.__objectNames[173] = "CharacterPortraitAnimation";
	global.__objectNames[174] = "ScoutPortraitAnimation";
	global.__objectNames[175] = "PyroPortraitAnimation";
	global.__objectNames[176] = "SoldierPortraitAnimation";
	global.__objectNames[177] = "HeavyPortraitAnimation";
	global.__objectNames[178] = "DemomanPortraitAnimation";
	global.__objectNames[179] = "MedicPortraitAnimation";
	global.__objectNames[180] = "EngineerPortraitAnimation";
	global.__objectNames[181] = "SpyPortraitAnimation";
	global.__objectNames[182] = "SniperPortraitAnimation";
	global.__objectNames[183] = "RandomPortraitAnimation";
	global.__objectNames[184] = "CTFHUD";
	global.__objectNames[185] = "InvasionHUD";
	global.__objectNames[186] = "ControlPointHUD";
	global.__objectNames[187] = "FauxCPHUD";
	global.__objectNames[188] = "ArenaHUD";
	global.__objectNames[189] = "KothHUD";
	global.__objectNames[190] = "GeneratorHUD";
	global.__objectNames[191] = "DKothHUD";
	global.__objectNames[192] = "TeamDeathmatchHUD";
	global.__objectNames[193] = "TeamSelectController";
	global.__objectNames[194] = "ClassSelectController";
	global.__objectNames[195] = "BubbleMenuZ";
	global.__objectNames[196] = "BubbleMenuX";
	global.__objectNames[197] = "BubbleMenuC";
	global.__objectNames[198] = "ScoreTableController";
	global.__objectNames[199] = "HUD";
	global.__objectNames[200] = "KillLog";
	global.__objectNames[201] = "RespawnTimer";
	global.__objectNames[202] = "SentryHealthHud";
	global.__objectNames[203] = "NutsNBoltsHud";
	global.__objectNames[204] = "SandwichHud";
	global.__objectNames[205] = "UberHud";
	global.__objectNames[206] = "StickyCounter";
	global.__objectNames[207] = "AmmoCounter";
	global.__objectNames[208] = "DeathCam";
	global.__objectNames[209] = "HealthHud";
	global.__objectNames[210] = "MedicRadar";
	global.__objectNames[211] = "WinBanner";
	global.__objectNames[212] = "HealedHud";
	global.__objectNames[213] = "HealingHud";
	global.__objectNames[214] = "CollisionMapO";
	global.__objectNames[215] = "Point";
	global.__objectNames[216] = "CustomMapO";
	global.__objectNames[217] = "PumpkinGib";
	global.__objectNames[218] = "Ghost";
	global.__objectNames[219] = "Money";
	global.__objectNames[220] = "Tombstone";
	global.__objectNames[221] = "RoomChangeObserver";
	global.__objectNames[222] = "Updater";
	global.__objectNames[223] = "RateController";
	global.__objectNames[224] = "PluginEnvironment";


	// create another array that has the correct entries
	var len = array_length_1d(global.__objectDepths);
	global.__objectID2Depth = [];
	for( var i=0; i<len; ++i ) {
		var objID = asset_get_index( global.__objectNames[i] );
		if (objID >= 0) {
			global.__objectID2Depth[ objID ] = global.__objectDepths[i];
		} // end if
	} // end for


}
